// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaApi.Data;

#nullable disable

namespace VeterinariaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618025128_Ciudad")]
    partial class Ciudad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaApi.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRegion")
                        .HasColumnType("int");

                    b.Property<string>("NombreCiudad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdRegion");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Regiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Ciudad", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Regiones", "NombreRegion")
                        .WithMany()
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombreRegion");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Regiones", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paises", "NombrePais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombrePais");
                });
#pragma warning restore 612, 618
        }
    }
}
