// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaApi.Data;

#nullable disable

namespace VeterinariaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225141717_Update-Login")]
    partial class UpdateLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaApi.Models.Acciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreAcciones")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("VeterinariaApi.Models.ActivosFijos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<int>("CategoriaActivoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoAdquisicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreActivo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<string>("UbicacionFisica")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("VidaUtil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaActivoId");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.HasIndex("SucursalId");

                    b.ToTable("ActivosFijos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.AusenciaEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<int>("AprobadoPorEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoAusenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorEmpleado");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TipoAusenciaId");

                    b.ToTable("AusenciaEmpleado");
                });

            modelBuilder.Entity("VeterinariaApi.Models.CategoriaActivoFijo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCategoriaActivoFijo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCategoriaActivoFijo")
                        .IsUnique();

                    b.ToTable("CategoriaActivoFijo");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("NombreCiudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("VeterinariaApi.Models.ConceptoNominas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong?>("EsFijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreNomina")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoConcepto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreNomina")
                        .IsUnique();

                    b.ToTable("ConceptoNominas");
                });

            modelBuilder.Entity("VeterinariaApi.Models.CriteriosEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCriterio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoCriterio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCriterio")
                        .IsUnique();

                    b.ToTable("CriterioEvaluacion");
                });

            modelBuilder.Entity("VeterinariaApi.Models.CursoCapacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Duracion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCurso")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCurso")
                        .IsUnique();

                    b.ToTable("CursoCapacitacion");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Departamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreDepartamento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreDepartamento")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EmpleadoCapacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAprobacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Capacitacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId")
                        .IsUnique();

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.HasIndex("Fecha_Capacitacion")
                        .IsUnique();

                    b.ToTable("EmpleadoCapacitacion");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EmpleadoEsepecialidad", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("FechaCertificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EmpleadoId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("EmpleadoEsepecialidad");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ci")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodEmpleado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Empleado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaContratacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodEmpleado")
                        .IsUnique();

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nit")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("NumeroTrabajadores")
                        .HasColumnType("int");

                    b.Property<string>("PlanSuscripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EspecialidadesMedicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreEspecialidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreEspecialidad")
                        .IsUnique();

                    b.ToTable("EspecialidadesMedicas");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EvaluacionEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("longtext");

                    b.Property<int>("CriterioEvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluadoPorEmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Evaluacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CriterioEvaluacionId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EvaluadoPorEmpleadoId");

                    b.ToTable("EvaluacionEmpleado");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Contrasena")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Tokens")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Login");
                });

            modelBuilder.Entity("VeterinariaApi.Models.LoginAcciones", b =>
                {
                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<int>("ReglasId")
                        .HasColumnType("int");

                    b.HasKey("LoginId", "ReglasId");

                    b.HasIndex("ReglasId");

                    b.ToTable("LoginAcciones");
                });

            modelBuilder.Entity("VeterinariaApi.Models.LoginMenu", b =>
                {
                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("LoginId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("LoginMenus");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreModulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreModulo")
                        .IsUnique();

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.MovimientosNomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<int>("ConceptoNominaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaMovimiento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PeriodoNomina")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("RegistradorPorEmpleado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("RegistradorPorEmpleado");

                    b.ToTable("MovimientosNomina");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Regiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("NombreDepartamento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.HasIndex("NombreDepartamento")
                        .IsUnique();

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreRol")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VeterinariaApi.Models.SubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("NombreSubModulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("NombreSubModulo")
                        .IsUnique();

                    b.ToTable("SubModulos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Sucursales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<string>("NombreSucursal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmailContacto")
                        .IsUnique();

                    b.HasIndex("IdCiudad");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("VeterinariaApi.Models.TipoAusencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreAusencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<ulong>("RequiereAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.HasKey("Id");

                    b.HasIndex("NombreAusencia")
                        .IsUnique();

                    b.ToTable("TipoAusencia");
                });

            modelBuilder.Entity("VeterinariaApi.Models.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<ulong?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.Property<string>("NombreTipo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoClientes");
                });

            modelBuilder.Entity("VeterinariaApi.Models.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("NombreTurno")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreTurno")
                        .IsUnique();

                    b.ToTable("TipoTurno");
                });

            modelBuilder.Entity("VeterinariaApi.Models.TurnosEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<ulong>("Confirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TurnoId");

                    b.ToTable("TurnosEmpleado");
                });

            modelBuilder.Entity("VeterinariaApi.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("VeterinariaApi.Models.UsuarioSucursal", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<ulong?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(1ul);

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "SucursalId");

                    b.HasIndex("SucursalId");

                    b.ToTable("UsuarioSucursal");
                });

            modelBuilder.Entity("VeterinariaApi.Models.ActivosFijos", b =>
                {
                    b.HasOne("VeterinariaApi.Models.CategoriaActivoFijo", "CategoriaActivoFijo")
                        .WithMany()
                        .HasForeignKey("CategoriaActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Sucursales", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaActivoFijo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VeterinariaApi.Models.AusenciaEmpleado", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Empleados", "AprobadoPorEmpleados")
                        .WithMany()
                        .HasForeignKey("AprobadoPorEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Empleados", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.TipoAusencia", "TipoAusencia")
                        .WithMany()
                        .HasForeignKey("TipoAusenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprobadoPorEmpleados");

                    b.Navigation("Empleado");

                    b.Navigation("TipoAusencia");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Ciudad", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paises", "NombrePaises")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombrePaises");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EmpleadoCapacitacion", b =>
                {
                    b.HasOne("VeterinariaApi.Models.CursoCapacitacion", "CursoCapacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Empleados", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CursoCapacitacion");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EmpleadoEsepecialidad", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Empleados", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.EspecialidadesMedicas", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Empleados", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Departamentos", "NombreDepartamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento");

                    b.HasOne("VeterinariaApi.Models.Sucursales", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal");

                    b.Navigation("NombreDepartamento");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Empresa", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paises", "NombrePais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombrePais");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EvaluacionEmpleado", b =>
                {
                    b.HasOne("VeterinariaApi.Models.CriteriosEvaluacion", "CriterioEvaluacion")
                        .WithMany()
                        .HasForeignKey("CriterioEvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Empleados", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Empleados", "EmpleadoEvaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadoPorEmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriterioEvaluacion");

                    b.Navigation("Empleado");

                    b.Navigation("EmpleadoEvaluador");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Login", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Empleados", "NombreEmpleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado");

                    b.Navigation("NombreEmpleado");
                });

            modelBuilder.Entity("VeterinariaApi.Models.LoginAcciones", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Acciones", "Regla")
                        .WithMany()
                        .HasForeignKey("ReglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("Regla");
                });

            modelBuilder.Entity("VeterinariaApi.Models.LoginMenu", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("VeterinariaApi.Models.MovimientosNomina", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Empleados", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Empleados", "RegistradorPorEmpleados")
                        .WithMany()
                        .HasForeignKey("RegistradorPorEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("RegistradorPorEmpleados");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Regiones", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paises", "NombrePais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombrePais");
                });

            modelBuilder.Entity("VeterinariaApi.Models.SubModulo", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Modulo", "NombreModulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombreModulo");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Sucursales", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Ciudad", "NombreCiudad")
                        .WithMany()
                        .HasForeignKey("IdCiudad");

                    b.Navigation("NombreCiudad");
                });

            modelBuilder.Entity("VeterinariaApi.Models.TurnosEmpleado", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Empleados", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Sucursales", "Sucursales")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.TipoTurno", "Turnos")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("Sucursales");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.UsuarioRol", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Login", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VeterinariaApi.Models.UsuarioSucursal", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Sucursales", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Login", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
