// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaApi.Data;

#nullable disable

namespace VeterinariaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaApi.Models.Acciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreAcciones")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRegion")
                        .HasColumnType("int");

                    b.Property<string>("NombreCiudad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdRegion");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Departamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Ci")
                        .HasColumnType("longtext");

                    b.Property<string>("CodEmpleado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VeterinariaApi.Models.EspecialidadesMedicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreEspecialidad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EspecialidadesMedicas");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Tokens")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("VeterinariaApi.Models.LoginMenu", b =>
                {
                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<int>("SubMenuId")
                        .HasColumnType("int");

                    b.HasKey("LoginId", "SubMenuId");

                    b.HasIndex("SubMenuId");

                    b.ToTable("LoginMenus");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreModulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Regiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreRol")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VeterinariaApi.Models.SubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("NombreSubModulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("SubModulos");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Sucursales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<string>("NombreSucursal")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Ciudad", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Regiones", "NombreRegion")
                        .WithMany()
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombreRegion");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Empleados", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Departamentos", "NombreDepartamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento");

                    b.Navigation("NombreDepartamento");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Login", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Empleados", "NombreEmpleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado");

                    b.HasOne("VeterinariaApi.Models.Roles", "NombreRol")
                        .WithMany()
                        .HasForeignKey("IdRol");

                    b.HasOne("VeterinariaApi.Models.Sucursales", "NombreSucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal");

                    b.Navigation("NombreEmpleado");

                    b.Navigation("NombreRol");

                    b.Navigation("NombreSucursal");
                });

            modelBuilder.Entity("VeterinariaApi.Models.LoginMenu", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("SubMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Regiones", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paises", "NombrePais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombrePais");
                });

            modelBuilder.Entity("VeterinariaApi.Models.SubModulo", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Modulo", "NombreModulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombreModulo");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Sucursales", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Ciudad", "NombreCiudad")
                        .WithMany()
                        .HasForeignKey("IdCiudad");

                    b.Navigation("NombreCiudad");
                });
#pragma warning restore 612, 618
        }
    }
}
